In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

***Segment Guests***
- In this session, we will segment and analyze guests so we can answer this question "Are there distinct types of guests?" by using K-Mean Clustering

In [5]:
data = pd.read_csv("../data/guest_survey_data.csv")
data

,guest_id,age,family_size,first_visit,visit_frequency,visit_motivation,venue,education_program,spending,satisfaction,learning_score,likelihood_return,likelihood_recommend,participated_booth
0,10001,56,3,no,First visit,Entertainment,Garden,No,14.617588,5.0,1.0,5.0,5.0,5
1,10002,69,5,no,Quarterly,Entertainment,Curiosity Museum,Yes,11.742618,5.0,3.0,5.0,5.0,5
2,10003,46,4,yes,Quarterly,Exhibits,Farm,No,15.875554,5.0,3.0,5.0,5.0,3
3,10004,32,5,no,Quarterly,Education,Farm,Yes,5.942116,4.0,2.0,3.0,4.0,3
4,10005,60,5,no,First visit,Family Time,Garden,No,9.851911,4.0,2.0,4.0,4.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,11196,23,6,no,First visit,Nature,Dinosaurs,No,6.918145,5.0,2.0,5.0,4.0,5
1196,11197,43,5,no,First visit,Family Time,Curiosity Museum,No,4.196820,5.0,3.0,4.0,5.0,1
1197,11198,71,6,no,First visit,Family Time,Dinosaurs,Yes,0.000000,5.0,3.0,5.0,4.0,5
1198,11199,21,3,no,First visit,Education,Garden,No,14.380630,4.0,3.0,5.0,4.0,2
1199,11200,36,3,no,Rarely,Nature,Garden,No,0.000000,5.0,2.0,5.0,4.0,5

In [14]:
features= data[["age","family_size","spending","satisfaction","learning_score","participated_booth"]]
scaler = StandardScaler()
X = scaler.fit_transform(features)
# Try 4 groups
kmeans = KMeans(n_clusters=4,random_state=42,n_init=10)

data["segment"] = kmeans.fit_predict(X)

# Now Profile
segment_profile = (data.groupby("segment")[["age",
                                            "family_size",
                                            "spending",
                                            "satisfaction",
                                            "learning_score",
                                            "participated_booth"]].mean())

segment_profile

,age,family_size,spending,satisfaction,learning_score,participated_booth
segment,,,,,,
0,46.145749,4.380567,33.731109,4.477733,3.659919,4.080972
1,47.778502,4.123779,13.600951,3.573290,3.397394,1.885993
2,55.130990,4.792332,9.740939,4.661342,2.869010,4.236422
3,36.813814,3.117117,9.730557,4.537538,3.816817,4.315315

***Segmentation Group***
1. Segment 0 - High spending visitors
   - high spending
   - medium - age, family size, satisfaction, learning_score, number of participating booth
2. Segment 1 - Experience-sensitive guests
   - low satisfaction, number of particiapting booth
   - meidum - age, family size, spending, learning score
3. Segment 2 - Mature visitors
   - high age
   - low spending, learning score
   - medium - family size, satisfaction, participating booth
4. Segment 3 - young familiys
   - low age, family size, spending
   - medium - satisfaction, learning score, participating booth