In [1]:
import numpy as np
import pandas as pd
import json

In [28]:
np.random.seed(42)
n=100000

##Household.csv
N_HOUSEHOLDS,MAX_VISITS = 100000, 12

households = pd.DataFrame({"household_id": [f"H{i:05d}" for i in range(1, N_HOUSEHOLDS + 1)]})

# Number of people in household
households["family_size"] = np.random.choice([2, 3, 4, 5, 6, 7],size=N_HOUSEHOLDS,p=[0.08, 0.15, 0.30, 0.25, 0.15, 0.07])

# Number of children
households["number_of_children"] = (households["family_size"] - np.random.choice([1, 2],size=N_HOUSEHOLDS, p=[0.20, 0.80]))

# Average age of children
households["children_age_avg"] = np.random.poisson(5, n)

# Num of visits
households["number_of_visits"] = np.random.choice(range(1, MAX_VISITS + 1), size=N_HOUSEHOLDS,p=[.2,.18,.15,.12,.1,.07,.05,.04,.03,.025,.02,.015])

households

,household_id,family_size,number_of_children,children_age_avg,number_of_visits
0,H00001,4,2,3,2
1,H00002,7,5,5,5
2,H00003,5,3,2,10
3,H00004,5,3,5,8
4,H00005,3,1,6,3
...,...,...,...,...,...
99995,H99996,6,4,6,4
99996,H99997,5,3,4,3
99997,H99998,5,4,6,10
99998,H99999,4,2,5,1
99999,H100000,4,3,5,3

In [30]:
## Children.csv
children_list = []

for _, household in households.iterrows():
    household_id = household["household_id"]
    number_of_children = household["number_of_children"]
    children_average_age = household

    for child_number in range(1, number_of_children + 1):
        child_id = f"{household_id}_C{child_number}"
        age = np.random.randint(3, 13)
        children_list.append({
            "child_id": child_id,
            "household_id": household_id,
            "child_number": child_number,
            "age": age
        })

children = pd.DataFrame(children_list)
children

          child_id household_id  child_number  age
0        H00001_C1       H00001             1    6
1        H00001_C2       H00001             2    6
2        H00002_C1       H00002             1    5
3        H00002_C2       H00002             2    5
4        H00002_C3       H00002             3   10
...            ...          ...           ...  ...
264669   H99999_C1       H99999             1    4
264670   H99999_C2       H99999             2   11
264671  H100000_C1      H100000             1    9
264672  H100000_C2      H100000             2    7
264673  H100000_C3      H100000             3    3

[264674 rows x 4 columns]